### ISSUE TITLE
DockerFile to start server.

### ISSUE THREAD

**Issue by codeperfectplus** [codePerfectPlus/cybel-discord.py#10]
**Is your feature request related to a problem? Please describe.**

adding a Docker file to start the server. 

For running instructions check README.md
Required:- Python3.9, requirements.txt is in the root directory

**Comment by tijmenstor** [comment]
Hey man, want to contribute here. You already have a Dockerfile in your repository, what is the difference with what you are trying to achieve with this?

**Comment by codeperfectplus** [comment]
The current Dockerfile doesn't have an environment variable like bot toke, and DB URL(mentioned in README).

**Comment by CreaTorAlexander** [comment]
I can work on this issue.

**Comment by CreaTorAlexander** [comment]
DISCORD_TOKEN: Discord bot token [get it from here](https://discord.com/developers/applications)
DATABASE_URL=postgres://username:password@localhost:5432/database_name

Basically this has to be added in the starting running process?

**Comment by codeperfectplus** [comment]
you can get an idea from [Stock Dashbaord](https://github.com/Py-Contributors/Stock-Dashboard), Dockerfile and docker-compose. 

it should take an env file like this to docker-compose.

```bash
docker-compose --env-file .env  up -d 
```


Reference:-
https://stackoverflow.com/questions/29377853/how-to-use-environment-variables-in-docker-compose
https://github.com/Py-Contributors/Stock-Dashboard

**Comment by CreaTorAlexander** [comment]
But for what reasons we have th start_server script?

**Comment by codeperfectplus** [comment]
but that will not work in a windows environment. most developers prefer docker so I was thinking to add proper docker files.
