### ISSUE TITLE
Can i update readme?

### ISSUE THREAD

**Issue by shubham7668** [codePerfectPlus/cybel-discord.py#13]
I want to create license link at the bottom
Can i do that?

**Comment by codeperfectplus** [comment]
Yes sure, but what do you want to change in README?

**Comment by shubham7668** [comment]
![image](https://user-images.githubusercontent.com/54644253/194781564-87c7c128-fc32-4344-bbdb-e10dff58c65e.png)
![image](https://user-images.githubusercontent.com/54644253/194781568-f99ae470-8fa7-4565-b6fe-41725d24cf26.png)
