### ISSUE TITLE
Upgrade from discord.py 1.7.1 to 2.0

### ISSUE THREAD

**Issue by Calciumcarbonate321** [codePerfectPlus/cybel-discord.py#18]
I think it will be great if we could bump the version of discord.py from 1.7.1 to 2.0. 
I'm willing to work on the breaking changes and get it up to date alongside adding in a very interesting feature(gameboy color emulator).

If that's fine then I can start work on it

**Comment by codeperfectplus** [comment]
@Calciumcarbonate321 I checked the documentation, and lots of things change in V2. Please let me know if you working on changes.

**Comment by Calciumcarbonate321** [comment]
I will start work on it from the weekend @codePerfectPlus 
EDIT:
I just saw that pull req, I'll work on other optimization stuff

**Comment by codeperfectplus** [comment]
I have updated the codes and tested them as well with V2. You can check V2.0.0 branch for changes. Still needs to update the code base according to V2 guidelines. There are few features in mind to work with.

**Comment by Calciumcarbonate321** [comment]
Will let you know what I'll be doing when starting work, hmu on discord CaCO3#9990
